### ISSUE TITLE
Add reviews page

### ISSUE THREAD

**Issue by bgins** [surge-synthesizer/surge-synth-team.org#16]
Let's consider adding links to reviews and mentions of the synths we work on. We could add a separate page, add a section to the "Join" page and rename it to "About", or maybe find some other place to collect these.

We can use this issue to start collecting reviews and mentions. The website for Surge is in another repo (https://github.com/surge-synthesizer/surge-synthesizer.github.io), but I'm thinking we can collect them all here because there will be some overlap. (We might want a separate issue anyways for discussing where to put them on the Surge site.) 

I'll start:

- Freebie(s) of the Month – SURGE, and Others: https://soundbytesmag.net/freebies-of-the-month-surge-and-others/

@tank-trax, @baconpaul , @mkruselj do you have some more to add here?

**Comment by baconpaul** [comment]
I know @tank-trax has been finding video reviews and adding them to the youtube. We could include those too. Good idea!

**Comment by bgins** [comment]
A couple of more reviews for when we get to this:

https://bedroomproducersblog.com/2020/07/30/surge-synth-update/
https://www.musictech.net/news/free-soft-synth-surge-gets-a-feature-packed-update/
https://www.synthtopia.com/content/2020/07/29/is-surge-the-ultimate-microtonal-synthesizer/

**Comment by tank-trax** [comment]
we have gathered a few good ones and I've a playlist too add, but was mulling it over. my idea is to put a small blurb and/or synopsis of the videos and reviews for each link... kind of a review of the review :-)

**Comment by bgins** [comment]
Yeah, good idea! It might also be good to categorize them. Something like version 1.7.0 reviews, reviews of microtuning features,  and so on.

**Comment by bgins** [comment]
A couple more:

https://www.synthanatomy.com/2020/07/surge-1-7-0-must-have-free-synthesizer-plugin-gets-a-massive-feature-update.html
https://www.softpedia.com/get/Multimedia/Audio/Audio-Mixers-Synthesizers/Surge-Synthesizer.shtml

One Synth Challenge pages:

https://www.kvraudio.com/forum/viewtopic.php?p=7359410#p7359410
https://www.kvraudio.com/forum/viewtopic.php?p=7848668

**Comment by bgins** [comment]
A intro tutorial: 

https://www.musictech.net/tutorials/weekend-workshop-make-your-first-sounds-with-surge-the-open-source-supersynth/

**Comment by bgins** [comment]
On Stochas:

https://www.youtube.com/watch?v=Wyx8cz7oxLI

**Comment by bgins** [comment]
Surge review:

https://www.youtube.com/watch?v=b9nZMV9gv1U
